### ISSUE TITLE
[BUG]: 无法本地调试代码

### ISSUE THREAD

**Issue by gittig11** [purocean/yn#176]
**Describe the bug**

## bug1

`yarn dev`时报错：
```
node_modules/domino/lib/sloppy.js:10:4: error: With statements cannot be used with the "esm" output format due to strict mode

10 │     with(this) eval(code);
   ╵     ~~~~
```

## bug2

`yarn start`时报错：
```
use proxy: false
envs: disable on windows
Address: http://localhost:3044
(node:3232) UnhandledPromiseRejectionWarning: Error: next() called multiple times
    at dispatch (...\YankNote\node_modules\koa-compose\index.js:36:45)
    at ...\YankNote\dist\main\server\index.js:767:21
    at step (...\YankNote\dist\main\server\index.js:63:23)
    at Object.next (...\YankNote\dist\main\server\index.js:44:53)
    at ...\YankNote\dist\main\server\index.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (...\YankNote\dist\main\server\index.js:34:12)
    at sendFile (...\YankNote\dist\main\server\index.js:755:12)
    at ...\YankNote\dist\main\server\index.js:762:42
    at step (...\YankNote\dist\main\server\index.js:63:23)
```
electron窗口黑色，没内容。

**Desktop (please complete the following information):**
 - Version: 3.31.0
 - OS: win10

**Comment by purocean** [comment]
node 版本是多少

**Comment by gittig11** [comment]
> node 版本是多少

16.13.2

**Comment by purocean** [comment]
试试14，我这里工作流里面用的 14。可以参考这个流程 https://github.com/purocean/yn/blob/develop/.github/workflows/release.yml
