### ISSUE TITLE
linux端使用求助

### ISSUE THREAD

**Issue by undefinedcodezhong** [purocean/yn#84]
下载安装了Yank-Note-linux-amd64-3.16.1.deb包，运行yank-note，报错信息如下：
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Yank Note/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Yank Note/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Yank Note/resources/app.asar/dist/main/server/index.js
- /opt/Yank Note/resources/app.asar/dist/main/app.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/Yank Note/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Yank Note/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Yank Note/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Yank Note/resources/app.asar/dist/main/server/index.js',
    '/opt/Yank Note/resources/app.asar/dist/main/app.js',
    undefined
  ]
}
```
似乎是缺少了某些js文件，请问应该怎么操作，对npm不熟，不太懂怎么解决

**Comment by purocean** [comment]
重新下载试试，之前 CI 跑得有问题

https://github.com/purocean/yn/releases/download/v3.16.1/Yank-Note-linux-amd64-3.16.1.deb

**Comment by purocean** [comment]
重新下载试试，之前 CI 跑得有问题

https://github.com/purocean/yn/releases/download/v3.16.1/Yank-Note-linux-amd64-3.16.1.deb
